#!/usr/bin/env -S bash -e
. "$(dirname "$0")"/../common.sh

[[ "$(bazel version | head -n1 | cut -d: -f2 | tr -d ' ')" =~ 0.15.*|0.16.* ]] || bazel build :events_proto

bazel build :events_scala
diff expected <(
    zipinfo -m -T --h-t "$(bazel info bazel-bin)/proto/events_scala.jar"
)
