# just for test of loading scala_deps; delete later
load("//scala_deps/src/bin:scala_deps.bzl", "scala_deps")

scala_deps(
    name = "generate_dependencies",
    src = "//scala_deps/src/bin:Deps.scala",
)
