workspace(name = "rules_scala3_test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

rules_jvm_external_tag = "56975243d79fd7db93a622579c107ad4b6c46f6e"

http_archive(
    name = "rules_jvm_external",
    sha256 = "b4e3a2acfbeacefe4073d68ef830ad79a847b1861682a64b4e555dfa48465b46",
    strip_prefix = "rules_jvm_external-{}".format(rules_jvm_external_tag),
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/{}.tar.gz".format(rules_jvm_external_tag),
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "org.scala-sbt:librarymanagement-core_3:2.0.0-M2",
        "org.scala-sbt:librarymanagement-coursier_3:2.0.0-alpha8",
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)

protobuf_tag = "28.2"

http_archive(
    name = "com_google_protobuf",
    sha256 = "b2340aa47faf7ef10a0328190319d3f3bee1b24f426d4ce8f4253b6f27ce16db",
    strip_prefix = "protobuf-" + protobuf_tag,
    url = "https://github.com/protocolbuffers/protobuf/archive/v{}.tar.gz".format(protobuf_tag),
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

rules_proto_tag = "6.0.2"

http_archive(
    name = "rules_proto",
    sha256 = "6fb6767d1bef535310547e03247f7518b03487740c11b6c6adb7952033fe1295",
    strip_prefix = "rules_proto-" + rules_proto_tag,
    urls = [
        "https://github.com/bazelbuild/rules_proto/archive/{}.tar.gz".format(rules_proto_tag),
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/{}.tar.gz".format(rules_proto_tag),
    ],
)

rules_cc_version = "0.0.9"

http_archive(
    name = "rules_cc",
    sha256 = "2037875b9a4456dce4a79d112a8ae885bbc4aad968e6587dca6e64f3a0900cdf",
    strip_prefix = "rules_cc-" + rules_cc_version,
    url = "https://github.com/bazelbuild/rules_cc/archive/{}.tar.gz".format(rules_cc_version),
)

rules_nixpkgs_tag = "705ee3b26cf49e990cddbbe6f60510fa46d50904"

http_archive(
    name = "io_tweag_rules_nixpkgs",
    sha256 = "f2c927815c18c088f02ff81caf9903f9c0b2596ac6e6bd40534bc299af9dc0d7",
    strip_prefix = "rules_nixpkgs-" + rules_nixpkgs_tag,
    url = "https://github.com/tweag/rules_nixpkgs/archive/{}.tar.gz".format(rules_nixpkgs_tag),
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")

rules_nixpkgs_dependencies()

# --

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_cc_configure", "nixpkgs_local_repository")

nixpkgs_local_repository(
    name = "nixpkgs",
    nix_file = "//:nixpkgs.nix",
    nix_file_deps = [
        "//:flake.lock",
        "//:flake.nix",
    ],
)

nixpkgs_cc_configure(repository = "@nixpkgs")

local_repository(
    name = "rules_scala3",
    path = "../",
)

load(
    "@rules_scala3//rules/scala:workspace.bzl",
    "scala_register_toolchains",
    "scala_repositories",
)

scala_repositories()

load("@rules_scala3//rules/scala:init.bzl", "rules_scala3_init")

rules_scala3_init()

scala_register_toolchains()

load("//3rdparty:workspace.bzl", "maven_dependencies")

maven_dependencies()

bind(
    name = "default_scala",
    actual = "@rules_scala3//scala:zinc_3_3",
)
