workspace(name = "rules_scala3_test")

load("@bazel_tools//tools/build_defs/repo:jvm.bzl", "jvm_maven_import_external")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

rules_jvm_external_tag = "d610f38add575692ae711a905822d65e126d96ae"

http_archive(
    name = "rules_jvm_external",
    sha256 = "2e8806a236baad8b65623afd93846f8eade0e2f74a3699adba2bdaf22a270c69",
    strip_prefix = "rules_jvm_external-{}".format(rules_jvm_external_tag),
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/{}.tar.gz".format(rules_jvm_external_tag),
)

local_repository(
    name = "rules_scala3",
    path = "../",
)

load(
    "@rules_scala3//rules/scala:workspace.bzl",
    "scala_register_toolchains",
    "scala_repositories",
)

scala_repositories()

load("@rules_scala3//rules/scala:init.bzl", "rules_scala3_init")

rules_scala3_init()

load("@annex//:defs.bzl", annex_pinned_maven_install = "pinned_maven_install")

annex_pinned_maven_install()

scala_register_toolchains()

load(
    "@rules_scala3//rules/scala_proto:workspace.bzl",
    "scala_proto_register_toolchains",
    "scala_proto_repositories",
)

scala_proto_repositories()

scala_proto_register_toolchains()

load("@annex_proto//:defs.bzl", annex_proto_pinned_maven_install = "pinned_maven_install")

annex_proto_pinned_maven_install()

load("@rules_scala3//rules/scalafmt:workspace.bzl", "scalafmt_default_config", "scalafmt_repositories")

scalafmt_repositories()

load("@annex_scalafmt//:defs.bzl", annex_scalafmt_pinned_maven_install = "pinned_maven_install")

annex_scalafmt_pinned_maven_install()

scalafmt_default_config()

load(":workspace.bzl", "test_dependencies")

test_dependencies()

load("@annex_test//:defs.bzl", annex_test_pinned_maven_install = "pinned_maven_install")

annex_test_pinned_maven_install()

jvm_maven_import_external(
    name = "junit",
    artifact = "junit:junit:4.12",
    artifact_sha256 = "59721f0805e223d84b90677887d9ff567dc534d7c502ca903c0c2b17f05c116a",
    server_urls = ["https://repo.maven.apache.org/maven2"],
)

jvm_maven_import_external(
    name = "hamcrest_core",
    artifact = "org.hamcrest:hamcrest-core:1.3",
    artifact_sha256 = "66fdef91e9739348df7a096aa384a5685f4e875584cce89386a7a47251c4d8e9",
    server_urls = ["https://repo.maven.apache.org/maven2"],
)

jvm_maven_import_external(
    name = "junit_interface",
    artifact = "com.novocode:junit-interface:jar:0.11",
    artifact_sha256 = "29e923226a0d10e9142bbd81073ef52f601277001fcf9014389bf0af3dc33dc3",
    server_urls = ["https://repo.maven.apache.org/maven2"],
)

bind(
    name = "default_scala",
    actual = "@rules_scala3//scala:zinc_3_0",
)
