#!/usr/bin/env -S bash -e
. "$(dirname "$0")"/../../common.sh

bazel build :0_used
! bazel build :0_unused || false
bazel build :0_unused |& grep "buildozer 'remove deps //3rdparty/jvm/org/scalacheck:scalacheck' //dependencies/unused:0_unused"
bazel build :0_unused_whitelist
