#!/usr/bin/env -S bash -e
. "$(dirname "$0")"/../../common.sh

bazel test --noworker_sandboxing --worker_extra_flag=ScalaCompile=--persistence_dir=.bazel-zinc --sandbox_debug --verbose_failures :tests
