#!/usr/bin/env -S bash -e
. "$(dirname "$0")"/../../common.sh

# rm -fr "$(bazel info execution_root)/.bazel-zinc"
bazel build --noworker_sandboxing --worker_extra_flag=ScalaCompile=--persistence_dir=/tmp/.bazel-zinc --worker_extra_flag=ScalaCompile=--extracted_file_cache=/tmp/.bazel-zinc-outputs :lib
