// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package auth

object RpcProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      auth.SignInReq,
      auth.SignInResp
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cg5ncnBjL3JwYy5wcm90bxIEYXV0aBoVc2NhbGFwYi9zY2FsYXBiLnByb3RvImEKCVNpZ25JblJlcRIpCgh1c2VybmFtZRgBI
  AEoCUIN4j8KEgh1c2VybmFtZVIIdXNlcm5hbWUSKQoIcGFzc3dvcmQYAiABKAlCDeI/ChIIcGFzc3dvcmRSCHBhc3N3b3JkIncKC
  lNpZ25JblJlc3ASMgoLYWNjZXNzVG9rZW4YASABKAlCEOI/DRILYWNjZXNzVG9rZW5SC2FjY2Vzc1Rva2VuEjUKDHJlZnJlc2hUb
  2tlbhgCIAEoCUIR4j8OEgxyZWZyZXNoVG9rZW5SDHJlZnJlc2hUb2tlbjI8CgtBdXRoU2VydmljZRItCgZTaWduSW4SDy5hdXRoL
  lNpZ25JblJlcRoQLmF1dGguU2lnbkluUmVzcCIAQh/iPxwQASgAOABCBlZlY3RvckgAYABoAHgAgAEAiAEBYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}