// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package auth

@SerialVersionUID(0L)
final case class SignInReq(
    username: _root_.scala.Predef.String = "",
    password: _root_.scala.Predef.String = ""
    ) extends scalapb.GeneratedMessage {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = username
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = password
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = username
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = password
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
    }
    def withUsername(__v: _root_.scala.Predef.String): SignInReq = copy(username = __v)
    def withPassword(__v: _root_.scala.Predef.String): SignInReq = copy(password = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = username
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = password
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(username)
        case 2 => _root_.scalapb.descriptors.PString(password)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = auth.SignInReq
    // @@protoc_insertion_point(GeneratedMessage[auth.SignInReq])
}

object SignInReq extends scalapb.GeneratedMessageCompanion[auth.SignInReq] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[auth.SignInReq] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): auth.SignInReq = {
    var __username: _root_.scala.Predef.String = ""
    var __password: _root_.scala.Predef.String = ""
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __username = _input__.readStringRequireUtf8()
        case 18 =>
          __password = _input__.readStringRequireUtf8()
        case tag => _input__.skipField(tag)
      }
    }
    auth.SignInReq(
        username = __username,
        password = __password
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[auth.SignInReq] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      auth.SignInReq(
        username = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        password = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = RpcProto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = RpcProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = auth.SignInReq(
    username = "",
    password = ""
  )
  final val USERNAME_FIELD_NUMBER = 1
  final val PASSWORD_FIELD_NUMBER = 2
  def of(
    username: _root_.scala.Predef.String,
    password: _root_.scala.Predef.String
  ): _root_.auth.SignInReq = _root_.auth.SignInReq(
    username,
    password
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[auth.SignInReq])
}
