#!/usr/bin/env -S bash -e
. "$(dirname "$0")"/../../common.sh

out_2_13=$(bazel test :mixed_2_13)
echo "$out_2_13" | grep 'should pop values in last-in-first-out order'
echo "$out_2_13" | grep 'JUnit many success'
