load("@rules_scala3//rules:scala.bzl", "scala_binary")

scala_binary(
    name = "one_discovered",
    srcs = ["one_discovered.scala"],
    scala = "@rules_scala3//scala:3_4",
    tags = ["manual"],
)
