name: Build Nix package on Ubuntu
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - id: bazel-rev
        run: echo "::set-output name=out::$(jq -r '.nodes.bazel.locked.rev' flake.lock)"

      - name: Cache install Nix packages
        uses: mtoohey31/cache-flake-attrs@v2
        with:
          flake_paths: .#devShell.x86_64-linux
          key: ${{ runner.os }}-nix-${{ steps.bazel-rev.outputs.out }}

      - name: Run specs
        run: >
          nix develop --experimental-features "nix-command flakes"
          --command bash -c ./scripts/test.sh &> log.txt; cat log.txt

      - name: Check for errors
        run: grep -F "[31m" log.txt && exit 1
